### ISSUE TITLE
Round-tripping TarReader/TarWriter

### ISSUE THREAD

**Issue by anaisbetts** [simolus3/tar#18]
I'm trying to write a function to round-trip a TAR archive in-place and edit some of the paths without having to expand it out and re-tar it (i.e. just read the archive and write it to a different file), but I'm running into a crash. Here's my code:

```dart
Future<void> convertArchBootstrapToWSLRootFs(
  String archImage,
  String targetRootfsFile,
) async {
  final inputStream = File(archImage).openRead().transform(gzip.decoder);

  await _getTarEntryStream(inputStream)
      .transform(tarWriter)
      .pipe(File(targetRootfsFile).openWrite());
}

Stream<TarEntry> _getTarEntryStream(Stream<List<int>> inputFile) async* {
  final reader = TarReader(inputFile);

  final initialFolder = RegExp(r'^root\.(x86_64|aarch64)\/');
  while (await reader.moveNext()) {
    final h = reader.current.header;
    final header = TarHeader(
      name: h.name.replaceFirst(initialFolder, ''),
      format: h.format,
      typeFlag: h.typeFlag,
      modified: h.modified,
      linkName: h.linkName,
      mode: h.mode,
      size: h.size,
      userId: h.userId,
      groupId: h.groupId,
      accessed: h.accessed,
      changed: h.changed,
      devMajor: h.devMajor,
      devMinor: h.devMinor,
    );

    yield TarEntry(header, reader.current.contents);
  }
}
```

results in this error:

```
_StreamController._subscribe (dart:async/stream_controller.dart:676)
_ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
_StreamImpl.listen (dart:async/stream_impl.dart:473)
new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49)
_BoundSinkStream.listen (dart:async/stream_transformers.dart:171)
Stream.forEach (dart:async/stream.dart:957)
_WritingSink._safeAdd 
_WritingSink.add.<anonymous closure>
_WritingSink._doWork.<anonymous closure> 
_rootRunUnary (dart:async/zone.dart:1434)
_CustomZone.runUnary (dart:async/zone.dart:1335)
<asynchronous gap> (Unknown Source:0)
_WritingSink.addStream ()
<asynchronous gap> (Unknown Source:0)
```

I suspect that this is because of how I'm passing along `reader.current.contents` without fully reading it out, but I'm not sure what to do in order to fix this. Any ideas?

**Comment by simolus3** [comment]
Interesting! Intuitively it looks like this should work (since you're not re-ordering tar contents or reading multiple source streams simultaneously). I'll take a look at what's going wrong here.

**Comment by simolus3** [comment]
I now understand what's happening here. In what's essentially a race condition, a call to `moveNext()` and the writer processing an event with the content stream is happening concurrently. As we only have a single source stream to listen to, this is going to blow up in some way. Here, it looks like `moveNext()` "won" and starts draining the contents of the entry to get to a point where the next entry can be read. Then, the writer attempts to read the stream which fails because `moveNext()` is currently draining it.

In 4b5f2e06ca69f2f935b11540862f51ee32a1e4fb, I've added defensive checks against this state to make sure that we provide more helpful error messages in this case. 

In your code, I'd just avoid using the intermediate stream for this case as there is no guarantee on when an item you emit is fully consumed, so you don't know when to go on. (Actually I think the writer should pause the source stream until it has fully processed an event, but `async*` is pretty bad at handling pauses - https://dartbug.com/34775). Instead, you can use a push-based writer that gives you a future for each entry:

```dart
Future<void> convertArchBootstrapToWSLRootFs(
  String archImage,
  String targetRootfsFile,
) async {
  final inputStream = File(archImage).openRead();
  final writer = tarWritingSink(File(targetRootfsFile).openWrite());
  final initialFolder = RegExp(r'^root\.(x86_64|aarch64)\/');

  await TarReader.forEach(inputStream, (entry) async {
    final h = entry.header;
    final header = TarHeader(
      name: h.name.replaceFirst(initialFolder, ''),
      format: h.format,
      typeFlag: h.typeFlag,
      modified: h.modified,
      linkName: h.linkName,
      mode: h.mode,
      size: h.size,
      userId: h.userId,
      groupId: h.groupId,
      accessed: h.accessed,
      changed: h.changed,
      devMajor: h.devMajor,
      devMinor: h.devMinor,
    );
    final newEntry = TarEntry(header, entry.contents);

    // We need to use addStream because `add` is synchronous in the `EventSink`
    // interface. This one ensures we've fully handled the entry.
    await writer.addStream(Stream.value(newEntry));
  });
}
```
