### ISSUE TITLE
[Question] How long it takes to combines multiple files

### ISSUE THREAD

**Issue by iosephmagno** [simolus3/tar#25]
Hello,

I'd need to tar a folder with 1000 small/medium files in it (avg file size 100KB). 
Do you have an idea about how long it would take doing that by using tar?

**Comment by simolus3** [comment]
I don't expect the package to add a noticeable overhead here, it should basically take as long as the individual reads and the write takes.

When you create a [TarEntry](https://pub.dev/documentation/tar/latest/tar/TarEntry-class.html), I recommend passing the stream from `File.openRead()` instead of reading the file into memory first. If you also set the size entry in the header of the entry, the tar package will be able to essentially forward all the streams into the new file.
