### ISSUE TITLE
Support skipping tar entries

### ISSUE THREAD

**Issue by simolus3** [simolus3/tar#6]
It should be possible to efficiently "skip" tar entries we're not interested in. For instance, consider something like

```dart
final reader = tar.Reader(file.openRead());
tar.Entry entry;
while ((entry = await reader.next() != null) {
  if (entry.typeFlag != tar.TypeFlag.reg || !myGlob.matches(entry.path)) continue;
  
  // read entry
}
```

I think the reader can just cancel the current substream when `next` gets called and the active stream hasn't been listened to.

**Comment by jonasfj** [comment]
Currently, if you forget to drain the entry, like:
```dart
void main() async {
  final tarStream = File('archive.tar').openRead().transform(reader);
  await for (final entry in tarStream) {
    await Future.delayed(Duration(milliseconds: 1));
    print(entry.name);
    // entry.drain(); // without this we only get the first file...
  }
}
```
Then reading of the remaining entries halts.

--------------------

I think this is why we want away from having a `Stream<Entry>` interface in the implementation we did with dart-neats.

Because if the user forgets to read the entries substream for an entry, then the reader completely halts. There could be an exception, a parsing error or something else that causes an entry to be only partially read.

Moreover, there is no way that the stream producer can throw an error or drain the substream, if the user forgets to drain the substream. Thus, it might be safest to move away from the `StreamTransformer` interface, as this is a pretty easy footgun for users to trigger :foot::gun: (and it's kind of hard to debug, especially when we can't even throw an error telling users what they did wrong).

-------------------------

I would suggest an interface like:
```dart
abstract class TarReader {
  factory TarReader(Stream<List<int>> tarStream) => ...
  /// Read next entry, false if we are EOF.
  ///
  /// Throws [StateError] if the [contents] from the previous entry have not been drained.
  Future<bool> next();

  /// Header for current entry, null if we are EOF, the call the next() haven't returned yet.
  Header header;

  /// Contents for current entry, null if we are EOF, the call the next() haven't returned yet.
  Stream<List<int>> contents;

  /// Utility function for quickly iterating through all entries in [tarStream].
  static Future<void> forEach(
    Stream<List<int>> tarStream,
    FutureOr<void> Function(Header header, Stream<List<int>> contents) action
  ) async {
    final reader = TarReader(tarStream);
    while(await reader.next()) {
      await action(reader.header, reader.contents);
    }
  }
}
```
Calling `reader.next()` is not as elegant, but it's simple and most people can figure it out --- and most importantly we can throw an error if they don't fully drain `contents` from the current entry before trying to read the next.

To make it even safer to use we could wrap the stream we return in `contents` with a `StreamController` such that we can detect if the user has started subscribing to it; and or fully consumed it.
This way, when `Reader.next()` is called we have the following cases:
 * `contents` is fully drained or cancelled, we continue reading the next entry.
 * Listen has never been called on `contents`, in this case it's probably safe to drain on behalf of the user.
 * `contents` have been listened to, but not fully consumed, we throw a `StateError`.
      * We could wait for `contents` to be fully consumed, but then if the user forgot we would just deadlock and not return the remaining entries from the tarStream -- which is the footgun we're trying to avoid building :D
      * We could also choose to drain `contents` on behalf of the user... But if the user is writing it to a file and forgot to await this operation, then the user will end up writing partial files in some cases (probably someone will experience that small files are successfully written, but large files are truncated, because this will be affected by events and timing).
      *  Throwing a `StateError` if not fully consumed is a bit crude, but at least it gives fairly consistent behavior.

-------

Another upside with an interface like this is that there is no need for an `Entry` class. The writer can just take `Writer.write(Header, Stream<List<int>>)`, and this might be better because you kind of want to encourage the user to do `await writer.write(header, File(...).openRead())` otherwise, the user will have multiple file streams open at once (not that this is a big deal). 


--------------------------------------------

I did a bit of digging and it seems streams in Dart are **not** required to suspend the same way asynchronous generators are in Javascript. Don't quote me on this, but try to run the following in on the Dart VM:

```
void main() async {
  final stream = () async* {
    print('Creating Object 1:');
    yield 'Object 1';

    // This is printed before "GOT: Object 1", is it weird that this surprises me?
    print('Creating Object 2:');
    yield 'Object 2';

    print('Creating Object 3:');
    yield 'Object 3';

    print('done');
  }();

  await for (final m in stream) {
    await Future.delayed(Duration(milliseconds: 1));
    print('Consumed: $m');
  }
}
``` 
You'll notice that "Creating Object 2", will be printed before "Consumed: Object 1" is printed.

I guess it makes sense that a stream of events should start producing the next event as soon as the first event has been accepted.

**Comment by jonasfj** [comment]
Another upside to doing the `TarReader` interface is that we can use `ChunkedStreamIterator` and have it be something like:

```dart
import 'package:pedantic/pedantic.dart' show unawaited;
import 'package:chunked_stream/chunked_stream.dart' show ChunkedStreamIterator;

class TarReader {
  final ChunkedStreamIterator<int> _input;

  TarReader(Stream<List<int>> tarStream)
      : _input = ChunkedStreamIterator(tarStream);

  Header? header;
  Stream<List<int>>? contents;

  Future<bool> next() async {
    // Prevent anyone from reading header while we're parsing
    header = null;
    contents = null;

    var block = await _input.readBlock();
    if (block.length < 512) {
      // We are EOF
    }
    if (block.isAllZeroes) {
      block = await _input.readBlock();
      if (block.isAllZeroes) {
        try {
          // there can be more blocks, if two tar files were concatenated
          block = await _input.readBlock();
        } on UnexpectedEOFException {
          return false; // here EOF is actually expected
        }
      }
    }

    final h = HeaderImpl.parseBlock(block);
    // TODO: read all the various PAX headers and GNU extensions, etc...

    header = h;
    contents = _input.substream(header.size);
    return true;
  }
}

extension on ChunkedStreamIterator<int> {
  Future<List<int>> readBlock() async {
    final block = await read(512):
    if (block.length < 512) {
      throw UnexpectedEOFException();
    }
    return block;
  }
}
```

Using `.read(512)` and `.substream(header.size)` from `ChunkedStreamIterator` will ideally make the code easier to read too :D
There will be no need to keep track of state outside of the `TarReader.next()` function. No need to propagate pause/resume. No need to manage buffers because the next chunk wasn't a fill 512 bytes. And no need to track if the user fully consumed `TarReader.contents` because `ChunkedStreamIterator` will throw  if `_input.substream` returned a non-empty substream that wasn't fully consumed, canceled or drained.

**Comment by simolus3** [comment]
Thanks for all the suggestions! I thought about it, and agree that emitting entries as a stream is just too easy to misuse. I'll adapt the reader to use the interface you suggested.

> To make it even safer to use we could wrap the stream we return in `contents` with a `StreamController` such that we can detect if the user has started subscribing to it; and or fully consumed it.

Agreed, I think we should handle the three cases you described. I need to wrap the internal stream either way, to guard against an unexpected EoF where `substream` would return fewer bytes than indicated in the header.

> I did a bit of digging and it seems streams in Dart are not required to suspend the same way asynchronous generators are in Javascript. Don't quote me on this, but try to run the following in on the Dart VM:

I think that's a bug in the VM though, it works on dartpad. https://dartbug.com/34775

**Comment by jonasfj** [comment]
> I think that's a bug in the VM though, it works on dartpad. https://dartbug.com/34775

Nice, find! 

Reading [the spec 17.6.3 (page 152)](https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf), it's also my understanding that any `await` inside the body of `await for` should pause the stream being consumed:
> Either execution of s is completely synchronous, or it contains an asynchronous construct (await, await for, yield or yield*) which will pause the stream subscription of its surrounding asynchronous loop.

**Comment by jonasfj** [comment]
Thinking more about this, if you have an instance of `Stream<Entry>` and you must drain `Entry.stream` before reading the next entry, then all of the utility method on [`Stream<T>`](https://api.dart.dev/stable/2.10.4/dart-async/Stream-class.html) are pretty much useless.

```dart
final entryStream = File('archive.tar').openRead().transform(tarReader);

// None of this methods on Stream<T> can work because they won't drain the substreams
await entryStream.length;
await entryStream.last;
await entryStream.any(...);
await entryStream.forEach(...);
await entryStream.contains(...);
await entryStream.skipWhile(...);
// etc...
```

The only sensible things you can do with an instance of `Stream<Entry>` is to use the `await for` syntax, or call `entryStream.asyncMap(...)`.

So returning an instance of `Stream<Entry>` is perhaps not very sensible, because you use it in most of the ways a normal `Stream<T>` can be used. You can't do something like:
```dart
// This won't work
final hasPubspec = File('archive.tar').openRead().transform(tarReader).any(
  (entry) => entry.header.name == 'pubspec.yaml'
);
```

Just sharing my notes here...


---------

@lrhn suggest we make `TarReader` a subclass of [StreamIterator](https://api.dart.dev/stable/2.10.4/dart-async/StreamIterator-class.html) which already has a `moveNext()` and a `current` property.
So something like:
```dart

class TarReader extends StreamIterator<Header> {
  @override
  Header get current;
  
  Stream<List<int>> get contents;

  @override
  Future<bool> moveNext() async {...}

  @override
  Future<void> cancel() async {...}
}
```

**Comment by simolus3** [comment]
Ah, TIL about `StreamIterator`!

> then all of the utility method on `Stream<T>` are pretty much useless.

Well, we implicitly `drain` the content stream if it's never listened to, so they should work in general. The hard part is deciding how long to wait before emitting another value since we're essentially a `Stream<Stream<List<int>>>`. When emitting an entry, we can't really know if anyone will ever listen to it or if we're supposed to `drain` it. 

In my old tar implementation, I always emitted data through the entry stream so it doesn't make a difference if one listens to the stream or not. That supports skipping entries, but you might miss parts of a file if you wait before listening (which is even worse). Oh well, `StreamIterator` it is.

**Comment by jonasfj** [comment]
> Well, we implicitly `drain` the content stream if it's never listened to, so they should work in general. The hard part is deciding how long to wait before emitting another value since we're essentially a `Stream<Stream<List<int>>>`.

That's true, then if https://dartbug.com/34775 was fixed it might work reasonably.

Anyways, let's not think too much about the interface, if it's reasonably simple and foolproof, we can always make it elegant later :D

> I always emitted data through the entry stream so it doesn't make a difference if one listens to the stream or not. That supports skipping entries, but you might miss parts of a file if you wait before listening (which is even worse).

So you made the entry stream into a Broadcast stream, otherwise you can't force the events out... Or well, if you do they become buffered in memory. I guess either scenario is kind of undesirable.

In any case, I'm guessing `StreamIterator` with `moveNext` will work well with `ChunkedStreamIterator` behind the scenes. If we need/want any modifications to `ChunkedStreamIterator` let me know. Maybe we should tweak it be `ChunkedStreamIterator<T extends List>` such that we can get `ChunkedStreamIterator<Uint8List>` -- or maybe we just need `Uint8ListStreamIterator` so as to not get too fancy with generics :)

**Comment by simolus3** [comment]
> If we need/want any modifications to `ChunkedStreamIterator` let me know

For performance, I think it would be great if we could pass a custom buffer implementation to the `chunked_stream` package. I haven't tested this, but I imagine that a `Uint8Buffer` from `package:typed_data` will be much more efficient than a general `List<int>`. We don't even need breaking changes for that, just an optional `List<T> Function() createBuffer`  parameter that would be used to create internal buffers. I can open a PR for that tomorrow.

**Comment by jonasfj** [comment]
I would avoid `package:typed_data` and just use `dart:typed_data`, recently they even added a [BytesBuilder](https://api.dart.dev/stable/2.10.4/dart-typed_data/BytesBuilder-class.html) for growing large buffers of bytes.

**Comment by lrhn** [comment]
One thing that makes this problem more problematic is that it's mixing two kinds of stream data.
Most streams are either stand-alone events (often broadcast streams) which can be handled independently, or they're streams of (chunks of) data where you need all of the parts for it to work (often single-subscription streams).

This stream has both: The individual headers, and the chunked content of the following file.
I can see why making it a stream of (header + stream of data) looks useful, but it is problematic because the underlying data comes from the same stream, so you have to skip data to get to the next header. With a "push" approach (streams), there is no good place to say that you *don't* want the data. It could be a broadcast data stream, but that's fragile and error-prone (you loop over the entries, then asynchronously open a file to pipe data into, and whoops, you missed the first chunk). The alternative is buffering entire files that you don't care about, which is also an issue. (At least they'd be GCed when the file has been read completely, and no-one is hanging onto the stream any more).

That is why I recommend something like `StreamIterator`, even though it's not a particularly good API either. It's heavily state-based, forcing you to do things in a specific order which isn't visible from the interface.
(You can only read `current` after `moveNext` has completed with true and until calling `moveNext` again. You cannot call `moveNext` while a `moveNext` call is waiting to complete. So, every member of the API can throw if you call it at the wrong time, which is why I consider it a problematic API.)

An alternative to `StreamIterator<Header>` with a `content` getter (or `currentContent`) is a `StreamIterator<TarFile>` with
```dart
abstract class TarFile {
  Header get header;
  Stream<Uint8List> get content;
}
```
That avoids adding an extra `content`/`currentContent` member to the interface, it will just be a plain `StreamIterator<TarFile>`.

Again, that value will only be *valid* until the next invocation of `moveNext`. If you call `moveNext` before starting to read `content`, it's now too late because we've already started skipping data to get to the next header.
That will have to be well documented (and it's another chance to throw a `StateError`, yey!)

It's possible to allow you to start reading content, and then call `moveNext` *before* the content has been fully read. That just means that we do something with the data we pass by on the way to the next header instead of ignoring it.
Or you can make `moveNext` throw if you call it while reading content. 

Having an internal state machine while processing a structured stream seems unavoidable. Then it's "just" a matter of figuring out which states are needed, and how to transition between them.

**Comment by jonasfj** [comment]
> That avoids adding an extra content`/`currentContent` member to the interface, it will just be a plain `StreamIterator<TarFile>`.

This is a nice suggestion, the we don't need to make a public subtype of `StreamIterator` we could just have a public function:
```dart
StreamIterator<TarFile> readTarStream(Stream<List<int>> tarStream) => ...
```

> It's possible to allow you to start reading content, and then call `moveNext` before the content has been fully read. That just means that we do something with the data we pass by on the way to the next header instead of ignoring it.

In this case it would also be reasonable to make `moveNext` wait until the full content has been read.
That will cause a deadlock, but unlike the case with `await for` the infinite blocking won't happen in stream which just ends without providing the rest of the tar entries.

In either case, it's always reasonable to process the entire content before calling `moveNext`, so throwing a `StateError` if `moveNext` is called before the content is read, is also fair -- and perhaps slightly more reliable as it discourages anyone from trying to `moveNext` without having finished reading the content and handled any errors that occured from reading the content.

**Comment by lrhn** [comment]
> In this case it would also be reasonable to make moveNext wait until the full content has been read.
That will cause a deadlock, but unlike the case with await for the infinite blocking won't happen in stream which just ends without providing the rest of the tar entries.

It will automatically delay completion until it reaches the next header in the source stream (or the end of the tar archive, then it will just complete with false).

There is no deadlock unless you start reading the `content` stream and then pause it and never resume. That's no more a deadlock to me than never calling `moveNext` again. Yes, you can stall a stream if you want to, but you actually have to explicitly ask for it.
And you can even decide to not honor the pause if someone calls `moveNext` and buffer the rest of the file instead.

So, states:

* Initial state: Not listening on source stream yet. No current. No calls to moveNext.
    * On `moveNext`: Start listening to source stream, go to Looking for Header.
    * On `cancel`: go to Done.
* Looking For Header: Pending `moveNext`. No-one is currently listening for data.
    * On `moveNext`, `cancel` or `current`: throw StateError
    * On source data, check for the start of a header, then read that header (might take multiple chunks). 
       When full header read, pause source stream, complete last `moveNext` with true, and go to Header Found.
    * On EOS, complete last `moveNext` with false. Go to Done.
* Header Found: `moveNext` has completed with true, and has not been called again. No-one is listening on data. Source stream is paused.
    * On `moveNext`: Resume source stream and go to Looking for Header. The current `current` object becomes invalid, and its
      `content` can no longer be listened to, even if it hasn't been listened to before.
    * On `current.content.listen`: Resume source stream and go to Reading Data. 
      The content stream can no longer be listened to (it's single subscription)
    * On `cancel`: Cancel source stream, go to Done.
* Reading Data: Someone has called `current.content.listen` and the data is not done yet, and that subscription has not been cancelled.
    * on `moveNext`: Go to Reading Data and Looking For Header. (If not respecting pause, resume source stream here if paused).
    * on data: Forward to listener (up to next header). If data complete, close content stream, pause source stream, and go to Idle.
    * on EOS: probably a malformed stream, so close content stream with an error, go to Done.
    * on content pause, pause source stream. Resume on content resume.
    * on content cancel, pause source stream and go to Idle.
* Idle: Source stream paused, noone reading data, no pending `moveNext` call.
    * on `moveNext`: resume source stream, go to Looking For Header.
    * on `cancel`: cancel source stream. Go to Done. 
    * on `current`, give existing value (if any), but stream cannot be listened to again.
* Reading Data and Looking For Header. Same as Reading Data except that there is a pending `moveNext`.
   * On `moveNext`, `current` or `cancel`: Throw StateError
   * On data: forward to listener (up to next header). If data complete, close content stream and go to Looking for Header.
   * On EOS: Probably a malformed source. Close content stream with an error. Complete `moveNext` with false and go to Done.
   * On content subscription pause: pause source stream. Resume on content resume. (If not respecting pause, ignore this line)
   * On content subscription cancel: go to Looking For Header
* Done. Source stream read to completion or stream-iterator cancelled. No `current`.
    * On `moveNext`: return a future already completed with false.
    * On `current`: throw StateError.  
    * On `cancel`: do nothing.

That's how I envision it, but obviously I could be missing some details of Tar-decoding. :smile:

Generally, no member of `StreamIterator` can be called while a `moveNext` result is pending. When it completes with `true`, all members can be used until the next call to `moveNext` (although using `moveNext` *after* `cancel` could also be made an error).
This propagates into the `content` stream which you can only start reading until the next `moveNext`, but you can keep reading after a `moveNext` if you started before. We just need to know whether you care about the data between the two headers or not, as signaled by calling `content.listen` before `moveNext`.

**Comment by simolus3** [comment]
Thanks a lot for the suggestions and the state machine definition. Another benefit of the `TarFile` class is that the writer can be a `Sink<TarFile>`.

For now, I think I'll simplify things by disallowing all concurrent reads, so `moveNext()` would throw if there's an active entry being listened to. That reduces the transitions I need to take care of, the rest is fairly straightforward to implement with `ChunkedStreamIterator.substream()` + `Stream.eventTransformed` to detect an unexpected EoS. That should cover most usage scenarios, I can always allow more concurrency later.
